
FROM golang:1.20 AS builder

WORKDIR /app

RUN go build -o app diskgebruik.go

FROM debian:latest

WORKDIR /app

COPY --from=builder /app/app .

COPY config.json /app/config.json

RUN chmod +x app

CMD ["./app"]

